### ISSUE TITLE
could not find valid underpass map file

### ISSUE THREAD

**Issue by XXILTeun** [NoxPhoenix/custom-map-loader#12]
could not find valid underpass map file after reinstalling both the applications

**Comment by XXILTeun** [comment]
I did select the right folder

**Comment by RemcoGoy** [comment]
I've had the same issue as well, when cloning the code and testing some stuff out, the fix for me would be to increase the fileSize check for the underpass file. I'll contact the author to see if we can get this fix released soon

**Comment by dolikemedo** [comment]
@RemcoGoy This worked for me too. 
In file: manageMapFiles.js
in func: isValidUnderPass.
My underpass file was actually larger.
so i also increased from 2438000 to 2538000 and my underpass file is: 2439321 bytes.

**Comment by Geeboki** [comment]
@RemcoGoy, @dolikemedo
Thank you very much guys, it works, I'm so happy! 

For those who want to play right now (like me) the fix is:

1) In CustomMapLoader folder find the file "manageMapFiles.js".  The default path is: 'C:\Users\USERNAME\AppData\Local\CustomMaploader\app-1.3.0\resources\app\lib'
2) Open the file with Notepad, press Ctrl+F and search for ''isValidUnderPass" function
3) 2 rows below, in "if (fileSize >= 2304605 || fileSize <= 2104605) return false;" increase the first number. For example in my case I had to increase 2304605 up to 2504605 bytes.
4) Save the file and run CustomMapLoader
5) Enjoy awesome Lethamyr maps again after a long (almost season-length) break!
